version: "3.7"

services:
    nginx:
        image: nginx:1.17-alpine
        volumes:
            - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./..:/app
        depends_on:
            - php

    php:
        image: jorge07/alpine-php:7.4-dev
        volumes:
            - ./..:/app
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=reporkeeper
