# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/Infrastructure/Symfony/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Http\Controllers\:
        resource: '../src/UI/Http/Controllers'
        tags: ['controller.service_arguments']

    # Buses
    App\Infrastructure\Shared\Bus\Query\MessengerQueryBus:
        arguments:
            $queryBus: '@query.bus'

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
            $commandBus: '@command.bus'

    App\Domain\Shared\Bus\Query\QueryBusInterface: '@App\Infrastructure\Shared\Bus\Query\MessengerQueryBus'
    App\Domain\Shared\Bus\Command\CommandBusInterface: '@App\Infrastructure\Shared\Bus\Command\MessengerCommandBus'

    # Handlers

    command_handlers:
        namespace: App\Application\Report\Command\
        resource: '%kernel.project_dir%/src/Application/Report/Command/**/*CommandHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers:
        namespace: App\Application\Report\Query\
        resource: '%kernel.project_dir%/src/Application/Report/Query/**/*QueryHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }
